// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/kainonly/ip2region-sync/api"
)

// Injectors from wire.go:

func NewAPI() (*api.API, error) {
	values, err := LoadValues()
	if err != nil {
		return nil, err
	}
	db, err := UseGorm(values)
	if err != nil {
		return nil, err
	}
	apiAPI := &api.API{
		Values: values,
		Db:     db,
	}
	return apiAPI, nil
}
